### ISSUE TITLE
mods to add plz

### ISSUE THREAD

**Issue by quantummadness** [FragsForSweg/project-minecraft#2]
### link
**client/server**
https://modrinth.com/mod/terralith
https://modrinth.com/mod/incendium
https://modrinth.com/mod/ct-overhaul-village
https://modrinth.com/mod/origins
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat
https://modrinth.com/mod/audioplayer
https://modrinth.com/mod/exotelcraft

**client**
https://modrinth.com/mod/xaeros-world-map
https://modrinth.com/mod/xaeros-minimap
https://modrinth.com/mod/sound-physics-remastered

**server**
https://modrinth.com/mod/additional-structures
https://modrinth.com/datapack/dungeons-and-taverns

### why add it?: 
these are pretty cool mods lol

**Comment by sweglord227** [comment]
you should note that we switched to forge 1.20.1 on a whim. closing this issue.
